name: Deploy

on:
  pull_request:
    types:
      - labeled

jobs:
  deploy-branch:
    name: "Deploy Branch"
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-1"
      - name: Install CDK deps
        run: |
          cd infra
          yarn install --frozen-lockfile
      - name: CDK Bootstrap
        run: |
          cd infra
          cdk bootstrap
      - name: CDK Synth
        run: |
          cd infra
          cdk synth
      - name: CDK Deploy
        run: |
          cd infra
          cdk deploy
